############################################################################
# apps/examples/gui/Makefile
#
# SPDX-License-Identifier: Apache-2.0
#
############################################################################

include $(APPDIR)/Make.defs

# LCD touch GUI demo built-in application info

PROGNAME = $(CONFIG_EXAMPLES_GUI_PROGNAME)
PRIORITY = $(CONFIG_EXAMPLES_GUI_PRIORITY)
STACKSIZE = $(CONFIG_EXAMPLES_GUI_STACKSIZE)
MODULE = $(CONFIG_EXAMPLES_GUI)

# LCD touch GUI demo

MAINSRC = gui_main.c

include $(APPDIR)/Application.mk
